### ISSUE TITLE
great thank you, I was facing another issue, we dont have expand all, collapse all, Select Opened file

### ISSUE THREAD

**Issue by Smssyed8** [epm-dev-priporov/idea-notes#11]
great thank you, I was facing another issue, we dont have expand all, collapse all, 
Also, I search a file in hierarchy, on search the file is shown and opens in intellij tab, however doesnt show and point to the file in Notes, explorer. As there are child hierarchy files which I want to open and interested in.

_Originally posted by @Smssyed8 in https://github.com/epm-dev-priporov/idea-notes/issues/7#issuecomment-1514322638_

**Comment by Smssyed8** [comment]
Can we use, 

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VirtualFileManager

class OpenInEditorAction(private val tree: NoteTree, value: String? = null) : AnAction(value) {

    override fun actionPerformed(e: AnActionEvent) {
        val node = tree.getSelectedNode() ?: return
        val file = node.virtualFile ?: return
        val project = e.project ?: return

        // Open file in editor
        FileEditorManager.getInstance(project).openFile(file, true)

        // Find PsiFile corresponding to the opened file
        val psiFile = file.toPsiFile(project) ?: return

        // Select PsiFile in Project view
        val virtualFile = psiFile.virtualFile
        val virtualFileUrl = virtualFile?.url ?: return
        val projectFile = VirtualFileManager.getInstance().findFileByUrl(virtualFileUrl) ?: return
        projectFile.selectInProjectView()
    }

    private fun VirtualFile.toPsiFile(project: Project): PsiFile? {
        return PsiManager.getInstance(project).findFile(this)
    }
}

**Comment by epm-dev-priporov** [comment]
@Smssyed8 I found the following solution. Intellij idea has "Other | Select File in Project View" hotkey, which works for any files and the default behaviour for search is not to navigate to found file. But using this hotkey idea jump to it, so the same feature will be added for the plugin. This is actually what I tried to implement before. Will be released soon, now I am testing it and wait for another issue PR

**Comment by epm-dev-priporov** [comment]
done

**Comment by Smssyed8** [comment]
Hmm, is this working? I tested it in the update, but it is not working it seems

**Comment by epm-dev-priporov** [comment]
> Hmm, is this working? I tested it in the update, but it is not working it seems

did you assigned the hotkey "Other | Select File in Project View"? it's working

**Comment by epm-dev-priporov** [comment]
...yes....doesn't work in case when TextEditor is not selected, in case of markdown for example
