### ISSUE TITLE
Search scope to upper case

### ISSUE THREAD

**Issue by epm-dev-priporov** [epm-dev-priporov/idea-notes#12]
Needed to change "notes" to uppercase

     val scope = GlobalSearchScope.filesScope(project, virtualFileContainer.getFiles(), "notes")

**Comment by gantanikhilraj** [comment]
I would like to work on this @epm-dev-priporov, assign it to me.

**Comment by gantanikhilraj** [comment]
So @epm-dev-priporov , I need to change the "notes" to upper case("NOTES") ? is that the issue. if not could you please brief me the issue.

**Comment by epm-dev-priporov** [comment]
@gantanikhilraj to "Notes"
![image](https://user-images.githubusercontent.com/30048339/233658255-7a0dca11-aa26-4ffd-b0c3-315e2f5dbfc3.png)
All other scopes start from upper latter, the same is expected for the plugin scope
