### ISSUE TITLE
After the upgrade ide version by jetbrains toolbox, all my saved bookmarks are rolled back to the previous year. 

### ISSUE THREAD

**Issue by ruzarh** [epm-dev-priporov/idea-notes#24]
After the upgrade Ide version by Jetbrains toolbox, all my saved bookmarks are rolled back to the previous year.  

How can I find them and attach them back?

**Comment by epm-dev-priporov** [comment]
@ruzarh Hi, seems that Intellij idea nested config isn't moved to new directory. All what you need is only copy i**deanotes.xml** file from previous version to new. For me in linux it's located in **~/.config/JetBrains/IdeaIC2023.1/options/ideanotes.xml**. Probably in the future it make sense to not rely on that idea nested feature and rewrite this functionality. Sorry for that bug, will create an issue to fix that in the future

**Comment by epm-dev-priporov** [comment]
please let me know if you fix the issue or you need assist for that

**Comment by ruzarh** [comment]
Thank you very much! Everything worked. I did it on the maс, maybe that’s the problem. 

IdeaNotes extension is very cool and convenient, thanks for the support and development of new functionality.
