### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.2)

### ISSUE THREAD

**Issue by chernyshev** [epm-dev-priporov/idea-notes#26]
Please add support for IDEA 2023.2

**Comment by epm-dev-priporov** [comment]
Hi @chernyshev
Thank you fo the report, the update 1.2.11 is already reviewing by JB. I think it will be available today/tomorrow

**Comment by epm-dev-priporov** [comment]
update is available, closed the issue
