### ISSUE TITLE
use new ui icon

### ISSUE THREAD

**Issue by guobin211** [epm-dev-priporov/idea-notes#29]
![image](https://github.com/epm-dev-priporov/idea-notes/assets/30451385/7c1d78ac-133a-4daf-ba16-5d8d7fbc071c)

**Comment by epm-dev-priporov** [comment]
Hello @guobin211 

Thank you for the report, but I would like to clarify some points

1) markdown icon is taken from new ui, what exactly do you suggest?
![image](https://github.com/epm-dev-priporov/idea-notes/assets/30048339/d80d920b-58f6-471b-a050-36ce41396c9a)

2) this is not related to the plugin, it seems that it's other plugin
![image](https://github.com/epm-dev-priporov/idea-notes/assets/30048339/0f7a0427-ed13-4483-b90b-bc0ef869bafa)

3) only this icons is realted to the plugin, that is actually what I am going to change in the following update
![image](https://github.com/epm-dev-priporov/idea-notes/assets/30048339/f15c7c62-7b6d-49ea-81be-674b86b5904c)

4) do you have any suggestions regarding this?
![image](https://github.com/epm-dev-priporov/idea-notes/assets/30048339/0f8bfcb7-80c6-475b-97f9-567d3184ae3e)

**Comment by epm-dev-priporov** [comment]
applied some changes accorind to the issue
