### ISSUE TITLE
Please choose a nice solid color icon

### ISSUE THREAD

**Issue by guobin211** [epm-dev-priporov/idea-notes#30]
Please choose a nice solid color icon

<img width="472" alt="image" src="https://github.com/epm-dev-priporov/idea-notes/assets/30451385/211bb83a-c11f-4aeb-b10f-d4bc3a023b6e">

**Comment by epm-dev-priporov** [comment]
@guobin211 hi
Thank you for the report, but I am afraid I have no idea what you are expecting. I would really appreciate if you share the icon which you want to see

**Comment by epm-dev-priporov** [comment]
@guobin211 Hello, could you please explain the issue, otherwise I close the ticket
