### ISSUE TITLE
CSV/TSV files open in an external editor, even when there's IDE support

### ISSUE THREAD

**Issue by ristomatti** [epm-dev-priporov/idea-notes#32]
Currently CSV/TSV files opens in a plain text editor external to my IDE (WebStorm). I would assume most users would expect the editor for a given file type is used (based on what plugin the files are associated with in the IDE settings). I can understand why someone would want to open the files in e.g Excel or LibreOffice Calc but this could be an option to show when right clicking a file, not the only to open them.

Editing CSV and TSV file support is included with the DataGrip IDE and as a plugin for IDEA Ultimate, WebStorm eg.
- https://www.jetbrains.com/help/idea/editing-csv-and-tsv-files.html
- https://plugins.jetbrains.com/plugin/10925-database-tools-and-sql-for-webstorm

There's also some popular 3rd party plugins:
- https://plugins.jetbrains.com/plugin/10037-csv-editor
- https://plugins.jetbrains.com/plugin/12896-rainbow-csv

This might apply to other file types supported by NotesTree as well.

**Comment by epm-dev-priporov** [comment]
Hello and thank you for the report. In early versions the plugin used csv-editor plugin , but then I decided to change it, so I think I will add configuration panel where user would be able to select default behaviour, are you ok with that solution?

**Comment by ristomatti** [comment]
Soud good to me. :+1:

**Comment by epm-dev-priporov** [comment]
completed in 1.3.2
