### ISSUE TITLE
Cannot see previous notes in AndroidStudio

### ISSUE THREAD

**Issue by muammil** [epm-dev-priporov/idea-notes#34]
I cannot see my previous notes from android studio, all the note files are still in the .ideanotes folder but the plugin only showing the new notes added today, new notes also getting saved to the same folder .ideanotes, don't know why the plug behave like this. The issue happened after updating the notes tree plugin to the latest version.
![Screenshot 2024-02-01 at 4 38 26 PM](https://github.com/epm-dev-priporov/idea-notes/assets/4345939/4e4f40d6-c3fb-4eab-92ed-ab4cacbfc7c8)

**Comment by epm-dev-priporov** [comment]
I am afraid this is my fail, all of them can be found in **~/.ideanotes/ directory**

**Comment by epm-dev-priporov** [comment]
fixed in 1.4.1, will be available after JB review. Please let me know in case of any issues
