### ISSUE TITLE
Notes Catastrophe: Losing All Data After Update

### ISSUE THREAD

**Issue by parhamPudding** [epm-dev-priporov/idea-notes#35]
After updating the notes tree, I have lost all my notes.

**Comment by epm-dev-priporov** [comment]
I am afraid this is my fail, all of them can be found in **~/.ideanotes/ directory**

**Comment by epm-dev-priporov** [comment]
fixed in 1.4.1, will be available after JB review. Please let me know in case of any issues

**Comment by parhamPudding** [comment]
Thank you for your help; it works fine, as always, just like before. Now I have all my text again.

**Comment by epm-dev-priporov** [comment]
@parhamPudding thank you for the feedback, I am glad to hear that it's fine!
