### ISSUE TITLE
Not compatible with the latest version of IDE (241)

### ISSUE THREAD

**Issue by komatebe** [epm-dev-priporov/idea-notes#37]
It gets disabled by the IDE with the following error message:
"Plugin error
Plugin 'NotesTree' (version '1.4.1') is not compatible with the current version of the IDE, because it requires build 233.* or older but the current build is PY-241.14494.241"

But I'm 100% positive you are aware of that :-)

Great plugin BTW!

**Comment by epm-dev-priporov** [comment]
Hello @komatebe .
Thank you for the issue and the feedback. The new compatible version will be available after JB review. Usually it takes 1-2 business days

**Comment by komatebe** [comment]
Thanks, @epm-dev-priporov 

This is great news. Thanks for your prompt response. 
Best!
