### ISSUE TITLE
Crashing on  idea 2024.1 when using normal intelij functions

### ISSUE THREAD

**Issue by Hardcore-fs** [epm-dev-priporov/idea-notes#38]
When trying to read a postgres database table def the tool causes a crash

IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 24
Metal Rendering is ON
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  org.dnltsk.mapfileplugin (7.0#0.5.2)
  Visual Paradigm SDE for IntelliJ IDEA (Community Edition) (2.0)
  appland.appmap (0.64.0)
  com.intellij.ml.llm (241.14494.320)
  com.haulmont.jpab (241.14494.158)
Kotlin: 241.14494.240-IJ

error message:

![Screenshot 2024-04-28 at 1 59 21 PM](https://github.com/epm-dev-priporov/idea-notes/assets/1309004/ee7b5525-8be6-43af-ab49-2d3d82b0f28e)

![error_prod](https://github.com/epm-dev-priporov/idea-notes/assets/1309004/bb55ea74-d0f7-4f47-be2d-be2adcd8343d)

**Comment by epm-dev-priporov** [comment]
@Hardcore-fs thank you for the report, could you please ad more details aboud reproducing issue?

**Comment by Hardcore-fs** [comment]
Hi,
no idea, recently after the latest idea update,  it is acting strangely....

also idea  is not able to read the postgresql database....

maybe they have an underlying problem, and your plugin assumes everything is ok.. and then errors, so idea points to your code.

my  postgres reads perfectly well on every database tool.
but one  database is not reading reliably in idea, the other databases are fine.

It throws errors about  IDEA submitting badly formed filters.. (which it uses to filter the correct schemas on a database connection.)
this errors.... is not fully trapped then flows thru the code into the plugins...

I submitted a bug report but have no reply, even i'm a fully paid up customer.

**Comment by Hardcore-fs** [comment]
ah i just got an update.... to the  issue.........

It's a known issue that should be fixed in the nearest update. Meanwhile you may try workaround: https://youtrack.jetbrains.com/issue/JPAB-2814/Error-trying-to-create-JPA-Entity-from-DB#focus=Comments-27-9700487.0-0
