### ISSUE TITLE
All notes files have been erased

### ISSUE THREAD

**Issue by Rmy5** [epm-dev-priporov/idea-notes#42]
All my notes files were suddenly erased after I did an export.
I had to re install the plugin because importing (notes backup) was making PhpStorm crash each time. 
After reinstall I could reimport my notes files from backup.

**Comment by epm-dev-priporov** [comment]
@Rmy5 hello and thank you for the report. What is the version PhpStorm you are using? Also what was the last version of the plugin? Could you please share the log error? All of that could help me to figure out the cause.

**Comment by Rmy5** [comment]
Hello @epm-dev-priporov, thanks for your response.

> PhpStorm 2024.2.3
Build #PS-242.23339.16, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 x86_64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.7
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 6
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  dev.priporov.idea.notes (1.5.0)


As for the logs I'm not sure which one would help ?
I found this in the "idea.log":

> 2024-10-08 10:08:38,577 [1262392] SEVERE - #dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction - `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.priporov.idea.notes]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.priporov.idea.notes]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
2024-10-08 10:08:38,579 [1262394] SEVERE - #dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction - PhpStorm 2024.2.3  Build #PS-242.23339.16
2024-10-08 10:08:38,579 [1262394] SEVERE - #dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction - JDK: 21.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-10-08 10:08:38,579 [1262394] SEVERE - #dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction - OS: Mac OS X
2024-10-08 10:08:38,580 [1262395] SEVERE - #dev.priporov.ideanotes.action.common.CopyFromIdeProjectStructureAction - Plugin to blame: NotesTree version: 1.5.0

Yesterday I exported my notes in a backup and today all the files were empty.
I had to import them again from the backup.

**Comment by epm-dev-priporov** [comment]
hank you, I will investigate the cause

**Comment by epm-dev-priporov** [comment]
@Rmy5  I would like to clarify 1 thing. All files were empty or the file tree structure in the plugin was lost and the plugin was empty?

**Comment by Rmy5** [comment]
@epm-dev-priporov All files were empty, the file tree structure was still present.

<img width="1591" alt="Capture d’écran 2024-10-08 à 09 46 09" src="https://github.com/user-attachments/assets/638b2bd5-ed20-4e2c-8fb7-4a2ed57ede75">

**Comment by Rmy5** [comment]
@epm-dev-priporov I have to say that besides this issue, I like the plugin very much and use it all the time.

**Comment by epm-dev-priporov** [comment]
> @epm-dev-priporov I have to say that besides this issue, I like the plugin very much and use it all the time.

Thank you much for the feedback! It really motivates me to improve it

**Comment by Rmy5** [comment]
Update: So on opening PhpStorm all my tree note files are empty again... not sure what triggers it...

**Comment by epm-dev-priporov** [comment]
No worries. I reproduced the issue and hope fixed it, now I am testing the solution, will be available soon

**Comment by Rmy5** [comment]
Ah nice ! Thanks.

**Comment by epm-dev-priporov** [comment]
@Rmy5, I would like to ask you to test new version, before I upload it to JB market(usually it takes a few days before be available for users). You can find 1.5.1-SNAPSHOT as a pre-release in https://github.com/epm-dev-priporov/idea-notes/releases and install it from zip file this way:
![image](https://github.com/user-attachments/assets/2816151a-ee80-4429-8686-8e0e50d5d8e6)
Please let me know in case of any issues.

**Comment by Rmy5** [comment]
@epm-dev-priporov I installed the 1.5.1 version and all seems to be fine. I tried importing, exporting, relaunching the app multiple time and everything seems to be fine !

**Comment by epm-dev-priporov** [comment]
Uploaded to JB market, I close the isse once it will be available there

**Comment by epm-dev-priporov** [comment]
Available in JB market place
