### ISSUE TITLE
Code blocks in Markdown

### ISSUE THREAD

**Issue by Z2Flow** [epm-dev-priporov/idea-notes#45]
Currently, if a new codeblock is created the type is `aiignore`.
Please add an option to specify the language—e.g. `ruby`

**Comment by epm-dev-priporov** [comment]
@Z2Flow That you for the report. 
I am not sure, that I got your point. The plugin is not responsible for markdown representing. The plugin keeps .md files, but other plugin represents these files( https://www.jetbrains.com/help/idea/markdown.html ). So I am afraid I have no way to fix this one.
